### ISSUE TITLE
[EPIC 2] Frontend Implementation

### ISSUE THREAD

**Issue by b3nedictvs** [SmartInvoiceXYZ/nouns-builder#2]
- both interfaces are the same with different buttons enabled for different actors
- [x] #6
    - proposal creation involves invoice creation
    - for each DAO the client address is hard coded in the smart contracts (it's supposed to be the address for each individual DAO)
    - there should be a multi-sig from the DAO
    - above requires a fall back, where the user can input a custom address
    - NICE-TO-HAVE/SUGGESTION: there should be a reference to their working groups, like a hats tree or an overview in their docs
- [x] #7
    - this is where the releasing, locking, and milestone management is done
    - extra button for releasing would be disabled for the recipient
    - the builder interface is not a Safe app yet
    - Parse proposal data to check if a smart invoice is being created and display all the details.
- [x] #8
     - need to match the designs to show milestones in the same way

## Questions
- Does the funding DAO have to pass a DAO proposal every time?
- Do we need to deploy a specific sub-graph?
    - We should be fine with cross-referencing the existing sub-graphs.
-...

**Comment by b3nedictvs** [comment]
We need to build in a distinction between DAO funding contracts and safe addresses. If a safe is used to fund and release, this should be done through the safe frontend. Otherwise, the frontend should create a DAO proposal.

**Comment by b3nedictvs** [comment]
@wtfsayo should check whether Nouns Builder is using subgraph.

**Comment by b3nedictvs** [comment]
@wtfsayo was exploring components for their dapp libraries. They are using accordeon. @wtfsayo needs the figma.

**Comment by b3nedictvs** [comment]
@dan13ram will be updating all packages to the latest version, so we are using them consistently.

**Comment by dan13ram** [comment]
All packages are upgraded to v `0.1.16`, we should be using this latest version on nouns builder.

**Comment by wtfsayo** [comment]
E2E testing required #22
