### ISSUE TITLE
Add conditional hiding functionality of input field if DAO address, i.e. client address can be found. Otherwise, revert to input field.

### ISSUE THREAD

**Issue by b3nedictvs** [SmartInvoiceXYZ/nouns-builder#23]
Related to #6

**Comment by b3nedictvs** [comment]
@scottrepreneur says:
> hopefully DAOs will have MS address
> 1. use MS address for client, if provided for DAO
> 2. show client in form if not provided for DAO

**Comment by wtfsayo** [comment]
done
