### ISSUE TITLE
Make usage of safety valve more intuitive

### ISSUE THREAD

**Issue by b3nedictvs** [SmartInvoiceXYZ/nouns-builder#33]
It needs 1 txn attempt for safety valve date error to show up. Another one to tell me it needs to be 30 days from now and yet another attempt to inform me I need to set it 30 days from the last milestone.

The expected behaviour should be: Show appropriate validation after 1st transaction queueing attempt

https://www.loom.com/share/722fe28707844b88be2560cf06ee445d?sid=533528ca-8067-4339-863b-ec2f92acf522

cc @scottrepreneur

**Comment by wtfsayo** [comment]
fixed this!

default error: `Safety valve date must be at least 30 days from today or the last milestone whichever is later.`
milestone error: `

if not last-milestone+30 days: `Safety valve date must be at least 30 days after the last milestone date`
