### ISSUE TITLE
[STORY 2-1] Smart Invoice proposal creation flow

### ISSUE THREAD

**Issue by wtfsayo** [SmartInvoiceXYZ/nouns-builder#6]
- [x]  #11 
- [x]  Collect proposal data
- [x]  Add milestones
- [x] Parse & Create Txn Data
- [x] Queue Txn
- [x] Display total on sidebar
- [x] Create default Project & Desc for First Party App

**Comment by b3nedictvs** [comment]
Add, remove milestone, validations are done. Uploading project image. 

Call data still needs to be enabled to be put into txn flow. 95% there

**Comment by b3nedictvs** [comment]
@dan13ram will test. One small hurdle is that we cannot get it deployed. There are many dependencies from Nouns Builder, which make deploying for testing by @benedictvscriticus or others difficult. Ample time and resources should be considered for the final deployment in our domain as well.

**Comment by b3nedictvs** [comment]
@wtfsayo will figure out the cleanest way to add the title and description for the proposal to the invoice metadata.

**Comment by scottrepreneur** [comment]
Options discussed (slightly preferred order, depending ease/devex)
- Swap out the Submit button functionality to pin the details when submit is clicked
- Ask for the proposal title and summary in the previous step
- Create a default title and description from DAO/proposal data

**Comment by wtfsayo** [comment]
> Options discussed (slightly preferred order, depending ease/devex)
> 
> * Swap out the Submit button functionality to pin the details when submit is clicked
> * Ask for the proposal title and summary in the previous step
> * Create a default title and description from DAO/proposal data


Got done with creation flow without Title & Desc!!!


1 & 2 are both equally *hacky* methods!!!
Leaning towards 3!

**Comment by wtfsayo** [comment]
feedback from @dan13ram 

- [x] treasury balance error display
- [x] Default Milestone Title 1...2
-  [x] Default New Milestone amount 0.5
- [x] Local form Store

**Comment by b3nedictvs** [comment]
@wtfsayo and @dan13ram tested this functionality. @dan13ram discovered an edge case in the bundler contract, where the contract did not account for native eth. He pushed an update, which is now in @wtfsayo's court.
