### ISSUE TITLE
[STORY 2-2] Smart Invoice Proposal view and management

### ISSUE THREAD

**Issue by wtfsayo** [SmartInvoiceXYZ/nouns-builder#7]
- [x] Display Proposed txn
- [x] Display milestones in accordian
- [x] Display correct state of milestones
- [x] decode escrowAddress from executionTxnHash etc
- [x] Create Release Proposal if client is Dao
- [x] Redirect to Safe if not above case

**Comment by wtfsayo** [comment]
Awaiting subgraph update!!! @dan13ram 

- To get invoice Address once proposal passed

**Comment by b3nedictvs** [comment]
@wtfsayo assuming that he has the escrow address, the FE can show the milestones and release functional. @wtfsayo is waiting for the subgraph provided by @dan13ram under #17 .

**Comment by b3nedictvs** [comment]
I.e. parsing of events is still needed.

**Comment by wtfsayo** [comment]
to be tested #22

**Comment by b3nedictvs** [comment]
Execution of the transaction is missing, as the Nouns builder has not previously build a treasury executed proposal. A button for creating a proposal on the treasury is needed.
